# Package Overview
package_name: flower_classification_model

# Data Files
training_data_file: Iris.csv

# Variables
# The variable we are attempting to predict (cnt)
target: Species

pipeline_name: flower_classification_model
pipeline_save_file: flower_classification__model_output_v

# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42

# Alogrithm parameters
n_estimators: 12
